### ISSUE TITLE
Requirements for maven central deployment

### ISSUE THREAD

**Issue by bmarwell** [java-native/jssc#23]
https://central.sonatype.org/pages/requirements.html

- [x] Correct Coordinates (tracked in #5 
- [x] Signing keys
- [x] Project Name, Description and URL
- [x] License Information #22
- [x] Developer Information
- [x] SCM information
- [x] distributionManagement tag.
- [x] add the sonatype plugin
- [x] Create a release profile
- [x] Take notes from https://github.com/acegi/acegi-standard-project about the GPG Key etc.

These needs to be added to the `pom.xml`.

### Setting up the release profile 

The release profile should include:

* javadoc
* java-sources
* signing

We can take a peek at projects like https://github.com/glowroot/glowroot/blob/12afc32250c96e25fa9e738fc997805b9529c368/pom.xml how they manage and implement the distribution management.

### How to deploy

```bash
 # snapshot deployment
mvn clean deploy

# release deployment
mvn versions:set -DnewVersion=1.2.3
mvn clean deploy -P release
```

### Requirements for Deployments

* Having an account at sonatype
  https://issues.sonatype.org/secure/Signup!default.jspa
* Having a GPG keypair

**Comment by heroichornet** [comment]
Can you deploy https://github.com/java-native/jssc/releases/tag/v2.9.1 to some maven repository distribution channel like maven central?

**Comment by bmhm** [comment]
Hi, I am currently not very much involved, because the discussion about the reproducible build ended nowhere. That said, I never added the relevant parts to the `pom.xml`. Maybe @tresf  or @woodrowbarlow  cann add a status update? Haven't looked into it for quite a while.

**Comment by bmhm** [comment]
@heroichornet  as a workaround, you could just clone this repository and type `mvn install`. If you have a proxy repository set up, you could also use `mvn deploy`.

**Comment by tresf** [comment]
I'm not yet versed with Maven, but would be happy to accept a PR.  Despite comments to the contrary, @bmhm is and always has been the project's Maven expert. 🍻

**Comment by bmhm** [comment]
Hi @tresf, thanks for the compliments! :)

To be able to create a single invocation with all resulting jars, we still would need a completly different project structure (as far as I can tell). 
However, I learned a bit of other possibilities in maven. We might also be able to compile the same project multiple times, for each desired architecture on a different build host (travis-ci for unix, etc.) and then collect all those artifacts and aggregate them in a final build.

Sadly, I do not know if I do find the time to look into this soon :( If I do, I will keep you updated!

**Comment by tresf** [comment]
@bmhm I agree that if we intend to fully automate the build process, the native libraries will need special build steps, especially those for Solaris, where CI environments are slightly harder to find.

That said, I don't think these automation steps are required for a maven release.  When the rest is ready, we should be able to release to maven with our existing binaries.  I cannot speak on behalf of rest of the steps.

**Comment by heroichornet** [comment]
Hi guys, thanks for the reply. I do have it working, but it would be cool if I could pull it directly. I understand if you don't have the time. Do I understand correctly. A PR would have to finish the tasks mentioned in the first post of this ticket?

**Comment by bmhm** [comment]
Hi @heroichornet,

not the time is the problem. Maven central does not allow to push artifacts with a groupId where you do not own the corresponding domain name.

That said, the next major version will probably contain some other group name and  package names so we can push our artifacts to maven central.

Until then, you could set up your own nexus or artifactory.

**Comment by bmhm** [comment]
Reminder to myself
https://github.com/stefanbirkner/travis-deploy-to-maven-central?files=1

**Comment by JockX** [comment]
Hi. As far as I can tell @bmhm has secured the access to [sonatype's repository](https://issues.sonatype.org/browse/OSSRH-54753) for updated groupId, the one with proffessional vibe to it as well, which brought my attention towards this fork. Is there a plan to manually upload the artifacts there soon, without worrying about automated build at this point? I did create a small PR with required pom.xml updates, that should allow it to go through.

**Comment by bmhm** [comment]
Hi,

I had the central release setup ready, you can still see it in my forked repo (v5 I created to seperate it).
@tresf  has the PGP private keys. I had sent him a copy when I was working on it.
To have access with your user, I can create a issue over at sonatype so your sonatype users have access.

Just tell me your user names and make sure the groupId is correct.

Best,
Ben

**Comment by tresf** [comment]
> @tresf has the PGP private keys. I had sent him a copy when I was working on it.

@bmhm any hints as to where this lives?  My records have Travis-CI and GnuPG passphrases, but no physical private-key that I can find.

**Comment by bmhm** [comment]
I sent it via slack. Either try to find the Slack private chat or the download folder where you store slack files. I don't know if I have another copy, but I can look. 

Anyway, new keys would also work after informing the sonatype team. That said, giving access to your users in the sonatype jira should have priority. Just send me your usernames, I'll create a jira ticket asap.

**Comment by tresf** [comment]
Quoting #general on the slack channel:

> I created a PGP key for signing the `.jar`s. I'd like to send you a copy and a copy of the password. It's name is [truncated]

It appears it was either not sent, or intentionally purged from PM history for security reasons.

> Anyway, new keys would also work after informing the sonatype team. That said, giving access to your users in the sonatype jira should have priority. Just send me your usernames, I'll create a jira ticket asap.

@JockX are you OK taking charge with this?  I should probably be added as a backup.  Which users are you referring to?  I assume it's not a sonatype JIRA account, but something else?

**Comment by JockX** [comment]
@tresf sure, I can help. My login for sonatype is jockx.

**Comment by tresf** [comment]
I registered for JIRA (I hope that's the right place?).  My name is tresf.

**Comment by bmhm** [comment]
The correct place is https://issues.sonatype.org/
Task is created: https://issues.sonatype.org/browse/OSSRH-59573

**Comment by bmhm** [comment]
> It appears it was either not sent, or intentionally purged from PM history for security reasons.

I can see if I find the keys and passphrase by tomorrow.

Here are the repositories I created:

- https://github.com/bmhm/jssc-native
- https://github.com/bmhm/libloader
- https://github.com/java-native/jssc/tree/jssc5

I did not delete them, because I thought you may want to look at it as a reference. Please also see the jssc5 branch where I refactored the whole pom structure.

I removed the other repositories from the project and removed myself as a member because I wasn't able to explain why I was doing this. I sincerly hope you can make use of my work anyway and it still is useful.
I had a full automated build ready (java libs, jar files with freshly compiled natives, upload to maven central snapshots).

HTH

**Comment by tresf** [comment]
@bmhm is there a chance the PGP key was uploaded to the repo as part of the jssc5 effort? https://github.com/java-native/jssc/tree/1c1e8bab141a139278609e990972851b1d0b6de8/.deployment

**Comment by tresf** [comment]
> I wasn't able to explain why I was doing this

I'd love to take this point into another topic because by proposing the links, you're also proposing that they may be useful and that they may eventually make it into the codebase.

When @bmhm left, the project was going from one code repository -- `jssc` -- and had split into three.

| Before | After |
|-------|-------|
| `jssc` (with 3rd party dependencies) | `jssc`, `jssc-native`, `libloader` |
| Manual builds | Fully automated builds |

... but this wasn't the only point of contention... collaboration actually started to decline over decisions over `native-lib-loader`, specifically:
1. Is it needed?  The old JSSC didn't have this additional dependency.
2. Should we write our own? (@bmhm spent a considerable amount of time doing just this)
3. How should it work (this was probably the biggest sticking point)

Although JSSC 2.9.1 uses a 3rd-party `native-lib-loader`, it had some scalability issues.  The upstream author was mostly receptive to these changes.  Quoting Slack:
    > I would rather not rely on a library which both we 1. do not control and 2. does not fit our needs.  [...] They accepted my PR by words, but never merged it

So `java-native/native-lib-loader` was born.

Two major concerns were raised:
* Caching (eventually acknowledged) https://github.com/bmhm/libloader/issues/6
* Runtime library-replacement (discussed in Slack but never acknowledged) 

The problem that I -- apparently wasn't communicating properly -- was that in old versions of JSSC, I could exploit the caching system to replace a `.dll|.so|.dylib` at runtime.  This was immensely helpful for ironing out #9 as well as https://github.com/qzind/tray/issues/414 (upstream bug report was deleted by scream3r, so this is the closest left on record).  My concern was that with an increased reliance on plugin systems, this type of live troubleshooting grew harder and harder for C++ developers to help.  Infact, I still whole-heartedly feel that splitting the project into so many sub-projects further obfuscates this for developers too (not just C++ developers).  As a reference, JNA builds for more platforms than JSSC and contains only a single repository: https://github.com/java-native-access.

So as to not undermine minimize or dismiss the hard work put into this project, I'd like to clearly state that "explaining how" was only one hurdle.  There were fundamental conflicting design opinions as well, ones which -- if the aforementioned links are to be used -- will ultimately come up again and will eventually need to be decided upon.

**Comment by bmhm** [comment]
I mostly agree to what you write, @tresf!

The idea of the `native-lib-loader` is that all system-specific binaries (`.dll`, `.so`, etc.) can be shipped with the library. Java does not have a native mechanism for this. The `native-lib-loader` will just extract once at startup the `.dll` or `.so` file (whichever needed) to a temp dir and load it.

The alternatives of not using such a mechanism are:
* Make the dev using this library (jssc) make the user extend his `-Dnative.lib.dir` (probably not a good idea)
* Every dev using this library (jssc) to include it into their startup script. They'd be forced to have one.

I wasn't satisfied with either of those two and liked the sneaky way of the original lib-loader and thus created our own (more verstile one) for a showcase.

tbh I really just wanted to create a showcase where we had a point of "full automation". It was never intended to implement it exactly this way. Just to show an idea what was possible and then to cherry-pick what we liked about it and to ditch what we do not need.

I agree, that all this is quite a lot to handle. But imho this is a result of java (and to some extend, maven, gradle, and the rest of the java ecosystem) poorly supporting native libraries.
