### ISSUE TITLE
org.slf4j.impl package is missing in jssc-2.9.2.jar version

### ISSUE THREAD

**Issue by rubenguies** [java-native/jssc#76]
Using eclipse in Windows 10, I'm getting these notifications. It looks like the org.slf4j.impl package is not present in the jssc-2.9.2.jar library.

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

![image](https://user-images.githubusercontent.com/76461022/102842807-f2bb3580-445b-11eb-9b96-b2ea5b4c7b04.png)

**Comment by pietrygamat** [comment]
This is quite natural, as the jssc is not bundling any logger implementation, only the API. The most hassle-free solution to suppress the warnig is probably to put [this jar](https://mvnrepository.com/artifact/org.slf4j/slf4j-api/1.7.25) in the classpath of your project. 

Note, that to my knowledge, the slf4j is only used by jssc's dependency - native lib loader, and by not having any logger on the classpath, you loose the ability to see the debug/error logs when initializing jssc, but it is optional and the library is otherwise functional.

**Comment by rubenguies** [comment]
Fixed adding the jar you recommended, thanks @pietrygamat
